# Generated by Django 4.2 on 2024-05-15 18:05

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_nombre', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('cliente_telefono', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Telefono de contacto')),
                ('cliente_direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('check_box', models.BooleanField(default=False)),
            ],
        ),
    ]
